name: farmassist
description: Precision farming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  clean_calendar: ^1.1.0
  cloud_firestore: ^4.17.2
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  firebase_messaging: ^14.9.1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  geolocator: ^11.0.0
  getwidget: ^4.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image: ^4.1.7
  image_cropper: ^6.0.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  page_transition: ^2.1.0
  pedantic: ^1.11.1
  provider: ^6.1.2
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model.tflite
    - assets/dict.txt

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular-webfont.ttf
